# Generated by Django 4.2.6 on 2023-10-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Apple', 'Apple'), ('Amazon', 'Amazon'), ('Steam', 'Steam'), ('eBay', 'eBay'), ('Xbox', 'Xbox'), ('Googleplay', 'Googleplay'), ('PlayStation', 'PlayStation'), ('Sephora', 'Sephora'), ('RazerGold', 'RazerGold'), ('Nordstrom', 'Nordstrom'), ('Nike', 'Nike'), ('MasterCard', 'MasterCard'), ('Vanilla', 'Vanilla Visa'), ('Wallmart Visa', 'Wallmart Visa'), ('Visa Slivery White', 'Visa Slivery White'), ('TT Visa', 'TT Visa'), ('Amex', 'Amex')], max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('EUR', 'EUR'), ('CAD', 'CAD')], max_length=5)),
                ('amount', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=50)),
                ('card_pin', models.CharField(blank=True, max_length=50, null=True)),
                ('exp_date', models.CharField(blank=True, max_length=10, null=True)),
                ('cvv', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
